"""add document_chunks table with french fulltext search

Revision ID: 5194b7e288c0
Revises: d6d2b687dea3
Create Date: 2026-08-05 03:21:26.111814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '5194b7e288c0'
down_revision = 'd6d2b687dea3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('chunk_id', sa.String(length=512), nullable=False),
    sa.Column('doc_id', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_file', sa.String(length=512), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('french', content)", persisted=True), nullable=False),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index('ix_document_chunks_search_vector', 'document_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_chunks_search_vector', table_name='document_chunks', postgresql_using='gin')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
